name: ci
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - name: Install
        run: poetry install --no-interaction
      - name: Lint
        run: pre-commit run --all-files
        env:
          LC_ALL: "C.UTF-8"
          LANG: "C.UTF-8"
          SKIP: "no-commit-to-branch"
      - name: Type check
        run: poetry run mypy .
      - name: Tests
        run: poetry run pytest
