name: release
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  id-token: write  # required for PyPI trusted publishing
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: abatilo/actions-poetry@v3
        with: { poetry-version: "1.8.3" }

      # Determine version bump from conventional commits since last tag
      - name: Bump version (conventional commits)
        id: bump
        run: |
          pip install commitizen
          cz bump --yes --changelog
          echo "version=$(python -c 'import tomllib,sys;print(tomllib.load(open(\"pyproject.toml\",\"rb\"))[\"tool\"][\"poetry\"][\"version\"])')" >> $GITHUB_OUTPUT
          
          # Push bump commit and tags back to origin
          git push --follow-tags
          echo "RELEASE_NEEDED=true" >> $GITHUB_ENV

      - name: Install & build
        run: |
          poetry install --no-interaction
          poetry build

      - name: Create GitHub Release
        if: env.RELEASE_NEEDED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.version }}
          generate_release_notes: true

      - name: Publish to PyPI (trusted publishing)
        if: env.RELEASE_NEEDED == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
